
underlay:
    loopback_ip: 172.1.1.2
    local:
        asn: 65001
    neighbors:

      - interface: xe-0/0/3
        name: leaf-02
        asn: 65003
        peer_ip: 100.0.1.7
        local_ip: 100.0.1.6

      - interface: xe-0/0/2
        name: leaf-01
        asn: 65002
        peer_ip: 100.0.1.5
        local_ip: 100.0.1.4
