
underlay:
    loopback_ip: 172.1.1.1
    local:
        asn: 65000
    neighbors:

      - interface: xe-0/0/3
        name: leaf-02
        asn: 65003
        peer_ip: 100.0.1.3
        local_ip: 100.0.1.2

      - interface: xe-0/0/2
        name: leaf-01
        asn: 65002
        peer_ip: 100.0.1.1
        local_ip: 100.0.1.0
