
underlay:
    loopback_ip: 172.1.1.6
    local:
        asn: 65003
    neighbors:

      - interface: xe-0/0/1
        name: spine-02
        asn: 65001
        peer_ip: 100.0.1.6
        local_ip: 100.0.1.7

      - interface: xe-0/0/0
        name: spine-01
        asn: 65000
        peer_ip: 100.0.1.2
        local_ip: 100.0.1.3
