---

############################################################
- name: Generate IP Fabric Configuration
  hosts: all
  connection: local
  vars:
     config_file_path: "{{ lookup('fileglob', '{{playbook_dir}}/host_vars/{{site}}/{{inventory_hostname}}/main.*') }}"

############################################################
  tasks:
############################################################
  - name: Deploy Configuration
    junos_config:
      check_commit: yes
      provider: "{{ credential }}"
      update: replace
      src: "{{ config_file_path }}"
      comment: "Pushed the configuration"
    register: config_result
    failed_when: config_result.failed == true
