---
  - name: getting underlay-ebgp vars
    include_vars:
      file: "{{playbook_dir}}/host_vars/{{site}}/{{inventory_hostname}}/generated-underlay-vars.yaml"

  - name: validate ebgp peers
    junos_command:
      provider: "{{ credential }}"
      display: 'xml'
      commands:
       - show bgp neighbor "{{ item.peer_ip }}"
      waitfor:
       - "result[0]['rpc-reply']['bgp-information']['bgp-peer']['peer-state'] eq 'Established'"
      retries: 3
      interval: 3
    register: response
    with_items:
    - "{{ underlay.neighbors }}"
    when: (item is defined)
    ignore_errors: True

  - name: print
    debug:
      var: response.msg

