---
  - name: getting underlay-ibgp vars
    include_vars:
      file: "{{playbook_dir}}/host_vars/{{site}}/{{inventory_hostname}}/generated-overlay.yaml"

  - name: validate ibgp peers
    junos_command:
      provider: "{{ credential }}"
      display: 'xml'
      commands:
       - show bgp neighbor {{ item }}
      waitfor:
       - "result[0]['rpc-reply']['bgp-information']['bgp-peer']['peer-state'] eq 'Established'"
      retries: 3
      interval: 3
    register: response
    with_items:
    - "{{ overlay.neighbors }}"
    when: (item is defined)
    ignore_errors: True

  - name: print
    debug:
      var: response.msg
  
